apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: db-deployment
spec:
  replicas: 1  
  # strategy:
  #   type: RollingUpdate
  selector:
    matchLabels:
      name: mysql
  template:
    metadata:
      labels:
        name: mysql
    spec:
      volumes:
        - name: mysql-db-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim    
      containers:
      - name: mysql
        image: mysql:5.7
        imagePullPolicy: Always
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"              
        ports:
        - name: mysql
          containerPort: 3306
        volumeMounts:
          - name: mysql-db-storage
            mountPath: /var/lib/mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: rootpassword
                optional: false
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: password
                optional: false
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: database-configmap
                key: MYSQL_DATABASE
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: database-configmap
                key: MYSQL_DATABASE_USER
          # - name: MYSQL_DATABASE_HOST
          #   valueFrom:
          #     configMapKeyRef:
          #       name: database-configmap
          #       key: MYSQL_DATABASE_HOST

