apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    name: mysql
spec:
  selector:
    name: mysql
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

