apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  labels:
    name: mysql
type: Opaque
data:
  password: QWExMjM0NQ==             #(Aa12345)
  rootpassword: emFiMTIzNDU2         #(zab123456)
  
