apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 3
  # minReadySeconds: 10  
  # # strategy:
  # #   type: RollingUpdate 
  # #   rollingUpdate:
  # #     maxUnavailable: 1 
  # #     maxSurge: 1  
  selector:
    matchLabels:
      name: web
  template:
    metadata:
      labels:
        name: web
    spec:
      containers: 
        - image: zabra/image-for-web-app:1.0
          imagePullPolicy: Always
          name: web
          ports: 
            - containerPort: 80
              protocol: TCP
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: database-configmap
                  key: MYSQL_DATABASE
            - name: MYSQL_DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: database-configmap
                  key: MYSQL_DATABASE_HOST
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: database-configmap
                  key: MYSQL_DATABASE_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: password
                  optional: false
      restartPolicy: Always
